// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gitlab

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab(in *jlexer.Lexer, out *UserBasic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "count":
			out.Count = int(in.Int())
		case "completed_count":
			out.CompletedCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab(out *jwriter.Writer, in UserBasic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Count))
	}
	{
		const prefix string = ",\"completed_count\":"
		out.RawString(prefix)
		out.Int(int(in.CompletedCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserBasic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserBasic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserBasic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserBasic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab(l, v)
}
func easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab1(in *jlexer.Lexer, out *TimeStatsModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "time_estimate":
			out.TimeEstimate = int(in.Int())
		case "total_time_spent":
			out.TotalTimeSpent = int(in.Int())
		case "human_time_estimate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.HumanTimeEstimate).UnmarshalJSON(data))
			}
		case "human_total_time_spent":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.HumanTotalTimeSpent).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab1(out *jwriter.Writer, in TimeStatsModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time_estimate\":"
		out.RawString(prefix[1:])
		out.Int(int(in.TimeEstimate))
	}
	{
		const prefix string = ",\"total_time_spent\":"
		out.RawString(prefix)
		out.Int(int(in.TotalTimeSpent))
	}
	if true {
		const prefix string = ",\"human_time_estimate\":"
		out.RawString(prefix)
		out.Raw((in.HumanTimeEstimate).MarshalJSON())
	}
	if true {
		const prefix string = ",\"human_total_time_spent\":"
		out.RawString(prefix)
		out.Raw((in.HumanTotalTimeSpent).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TimeStatsModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TimeStatsModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TimeStatsModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TimeStatsModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab1(l, v)
}
func easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab2(in *jlexer.Lexer, out *ReferencesModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "short":
			out.Short = string(in.String())
		case "relative":
			out.Relative = string(in.String())
		case "full":
			out.Full = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab2(out *jwriter.Writer, in ReferencesModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"short\":"
		out.RawString(prefix[1:])
		out.String(string(in.Short))
	}
	{
		const prefix string = ",\"relative\":"
		out.RawString(prefix)
		out.String(string(in.Relative))
	}
	{
		const prefix string = ",\"full\":"
		out.RawString(prefix)
		out.String(string(in.Full))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReferencesModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReferencesModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReferencesModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReferencesModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab2(l, v)
}
func easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab3(in *jlexer.Lexer, out *Milestone) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "iid":
			out.Iid = int(in.Int())
		case "group_id":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.GroupID).UnmarshalJSON(data))
			}
		case "project_id":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ProjectID).UnmarshalJSON(data))
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "due_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.DueDate).UnmarshalJSON(data))
			}
		case "start_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.StartDate).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdateAt).UnmarshalJSON(data))
			}
		case "expired":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Expired).UnmarshalJSON(data))
			}
		case "title":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Title).UnmarshalJSON(data))
			}
		case "description":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Description).UnmarshalJSON(data))
			}
		case "state":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.State).UnmarshalJSON(data))
			}
		case "web_url":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.WebURL).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab3(out *jwriter.Writer, in Milestone) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"iid\":"
		out.RawString(prefix)
		out.Int(int(in.Iid))
	}
	{
		const prefix string = ",\"group_id\":"
		out.RawString(prefix)
		out.Raw((in.GroupID).MarshalJSON())
	}
	{
		const prefix string = ",\"project_id\":"
		out.RawString(prefix)
		out.Raw((in.ProjectID).MarshalJSON())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"due_date\":"
		out.RawString(prefix)
		out.Raw((in.DueDate).MarshalJSON())
	}
	{
		const prefix string = ",\"start_date\":"
		out.RawString(prefix)
		out.Raw((in.StartDate).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdateAt).MarshalJSON())
	}
	{
		const prefix string = ",\"expired\":"
		out.RawString(prefix)
		out.Raw((in.Expired).MarshalJSON())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.Raw((in.Title).MarshalJSON())
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.Raw((in.Description).MarshalJSON())
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.Raw((in.State).MarshalJSON())
	}
	{
		const prefix string = ",\"web_url\":"
		out.RawString(prefix)
		out.Raw((in.WebURL).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Milestone) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Milestone) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Milestone) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Milestone) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab3(l, v)
}
func easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab4(in *jlexer.Lexer, out *MergeRequestModelSlice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(MergeRequestModelSlice, 0, 0)
			} else {
				*out = MergeRequestModelSlice{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 MergeRequestModel
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab4(out *jwriter.Writer, in MergeRequestModelSlice) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v MergeRequestModelSlice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MergeRequestModelSlice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MergeRequestModelSlice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MergeRequestModelSlice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab4(l, v)
}
func easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab5(in *jlexer.Lexer, out *MergeRequestModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "iid":
			out.Iid = int(in.Int())
		case "project_id":
			out.ProjectID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "state":
			out.State = string(in.String())
		case "imported":
			out.Imported = bool(in.Bool())
		case "imported_from":
			out.ImportedFrom = string(in.String())
		case "merged_by":
			if in.IsNull() {
				in.Skip()
				out.MergedBy = nil
			} else {
				if out.MergedBy == nil {
					out.MergedBy = new(UserModel)
				}
				easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in, out.MergedBy)
			}
		case "merge_user":
			if in.IsNull() {
				in.Skip()
				out.MergeUser = nil
			} else {
				if out.MergeUser == nil {
					out.MergeUser = new(UserModel)
				}
				easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in, out.MergeUser)
			}
		case "merged_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.MergedAt).UnmarshalJSON(data))
			}
		case "prepared_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.PreparedAt).UnmarshalJSON(data))
			}
		case "closed_by":
			if in.IsNull() {
				in.Skip()
				out.ClosedBy = nil
			} else {
				if out.ClosedBy == nil {
					out.ClosedBy = new(UserModel)
				}
				easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in, out.ClosedBy)
			}
		case "closed_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ClosedAt).UnmarshalJSON(data))
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		case "target_branch":
			out.TargetBranch = string(in.String())
		case "source_branch":
			out.SourceBranch = string(in.String())
		case "upvotes":
			out.Upvotes = int(in.Int())
		case "downvotes":
			out.Downvotes = int(in.Int())
		case "author":
			if in.IsNull() {
				in.Skip()
				out.Author = nil
			} else {
				if out.Author == nil {
					out.Author = new(UserModel)
				}
				easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in, out.Author)
			}
		case "assignee":
			if in.IsNull() {
				in.Skip()
				out.Assignee = nil
			} else {
				if out.Assignee == nil {
					out.Assignee = new(UserModel)
				}
				easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in, out.Assignee)
			}
		case "assignees":
			if in.IsNull() {
				in.Skip()
				out.Assignees = nil
			} else {
				in.Delim('[')
				if out.Assignees == nil {
					if !in.IsDelim(']') {
						out.Assignees = make([]UserModel, 0, 0)
					} else {
						out.Assignees = []UserModel{}
					}
				} else {
					out.Assignees = (out.Assignees)[:0]
				}
				for !in.IsDelim(']') {
					var v4 UserModel
					easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in, &v4)
					out.Assignees = append(out.Assignees, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "reviewers":
			if in.IsNull() {
				in.Skip()
				out.Reviewers = nil
			} else {
				in.Delim('[')
				if out.Reviewers == nil {
					if !in.IsDelim(']') {
						out.Reviewers = make([]UserModel, 0, 0)
					} else {
						out.Reviewers = []UserModel{}
					}
				} else {
					out.Reviewers = (out.Reviewers)[:0]
				}
				for !in.IsDelim(']') {
					var v5 UserModel
					easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in, &v5)
					out.Reviewers = append(out.Reviewers, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "source_project_id":
			out.SourceProjectID = int(in.Int())
		case "target_project_id":
			out.TargetProjectID = int(in.Int())
		case "labels":
			if in.IsNull() {
				in.Skip()
				out.Labels = nil
			} else {
				in.Delim('[')
				if out.Labels == nil {
					if !in.IsDelim(']') {
						out.Labels = make([]string, 0, 4)
					} else {
						out.Labels = []string{}
					}
				} else {
					out.Labels = (out.Labels)[:0]
				}
				for !in.IsDelim(']') {
					var v6 string
					v6 = string(in.String())
					out.Labels = append(out.Labels, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "draft":
			out.Draft = bool(in.Bool())
		case "work_in_progress":
			out.WorkInProgress = bool(in.Bool())
		case "milestone":
			if in.IsNull() {
				in.Skip()
				out.Milestone = nil
			} else {
				if out.Milestone == nil {
					out.Milestone = new(Milestone)
				}
				(*out.Milestone).UnmarshalEasyJSON(in)
			}
		case "merge_when_pipeline_succeeds":
			out.MergeWhenPipelineSucceeds = bool(in.Bool())
		case "merge_status":
			out.MergeStatus = string(in.String())
		case "detailed_merge_status":
			out.DetailedMergeStatus = string(in.String())
		case "sha":
			out.Sha = string(in.String())
		case "merge_commit_sha":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.MergeCommitSha).UnmarshalJSON(data))
			}
		case "squash_commit_sha":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.SquashCommitSha).UnmarshalJSON(data))
			}
		case "user_notes_count":
			out.UserNotesCount = int(in.Int())
		case "discussion_locked":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.DiscussionLocked).UnmarshalJSON(data))
			}
		case "should_remove_source_branch":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ShouldRemoveSourceBranch).UnmarshalJSON(data))
			}
		case "force_remove_source_branch":
			out.ForceRemoveSourceBranch = bool(in.Bool())
		case "allow_collaboration":
			out.AllowCollaboration = bool(in.Bool())
		case "allow_maintainer_to_push":
			out.AllowMaintainerToPush = bool(in.Bool())
		case "web_url":
			out.WebURL = string(in.String())
		case "references":
			if in.IsNull() {
				in.Skip()
				out.References = nil
			} else {
				if out.References == nil {
					out.References = new(ReferencesModel)
				}
				(*out.References).UnmarshalEasyJSON(in)
			}
		case "time_stats":
			if in.IsNull() {
				in.Skip()
				out.TimeStats = nil
			} else {
				if out.TimeStats == nil {
					out.TimeStats = new(TimeStatsModel)
				}
				(*out.TimeStats).UnmarshalEasyJSON(in)
			}
		case "squash":
			out.Squash = bool(in.Bool())
		case "squash_on_merge":
			out.SquashOnMerge = bool(in.Bool())
		case "task_completion_status":
			if in.IsNull() {
				in.Skip()
				out.TaskCompletionStatus = nil
			} else {
				if out.TaskCompletionStatus == nil {
					out.TaskCompletionStatus = new(UserBasic)
				}
				(*out.TaskCompletionStatus).UnmarshalEasyJSON(in)
			}
		case "has_conflicts":
			out.HasConflicts = bool(in.Bool())
		case "blocking_discussions_resolved":
			out.BlockingDiscussionsResolved = bool(in.Bool())
		case "approvals_before_merge":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ApprovalsBeforeMerge).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab5(out *jwriter.Writer, in MergeRequestModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"iid\":"
		out.RawString(prefix)
		out.Int(int(in.Iid))
	}
	{
		const prefix string = ",\"project_id\":"
		out.RawString(prefix)
		out.Int(int(in.ProjectID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"imported\":"
		out.RawString(prefix)
		out.Bool(bool(in.Imported))
	}
	{
		const prefix string = ",\"imported_from\":"
		out.RawString(prefix)
		out.String(string(in.ImportedFrom))
	}
	if in.MergedBy != nil {
		const prefix string = ",\"merged_by\":"
		out.RawString(prefix)
		easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out, *in.MergedBy)
	}
	if in.MergeUser != nil {
		const prefix string = ",\"merge_user\":"
		out.RawString(prefix)
		easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out, *in.MergeUser)
	}
	{
		const prefix string = ",\"merged_at\":"
		out.RawString(prefix)
		out.Raw((in.MergedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"prepared_at\":"
		out.RawString(prefix)
		out.Raw((in.PreparedAt).MarshalJSON())
	}
	if in.ClosedBy != nil {
		const prefix string = ",\"closed_by\":"
		out.RawString(prefix)
		easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out, *in.ClosedBy)
	}
	if true {
		const prefix string = ",\"closed_at\":"
		out.RawString(prefix)
		out.Raw((in.ClosedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"target_branch\":"
		out.RawString(prefix)
		out.String(string(in.TargetBranch))
	}
	{
		const prefix string = ",\"source_branch\":"
		out.RawString(prefix)
		out.String(string(in.SourceBranch))
	}
	{
		const prefix string = ",\"upvotes\":"
		out.RawString(prefix)
		out.Int(int(in.Upvotes))
	}
	{
		const prefix string = ",\"downvotes\":"
		out.RawString(prefix)
		out.Int(int(in.Downvotes))
	}
	if in.Author != nil {
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out, *in.Author)
	}
	if in.Assignee != nil {
		const prefix string = ",\"assignee\":"
		out.RawString(prefix)
		easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out, *in.Assignee)
	}
	{
		const prefix string = ",\"assignees\":"
		out.RawString(prefix)
		if in.Assignees == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Assignees {
				if v7 > 0 {
					out.RawByte(',')
				}
				easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out, v8)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"reviewers\":"
		out.RawString(prefix)
		if in.Reviewers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Reviewers {
				if v9 > 0 {
					out.RawByte(',')
				}
				easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out, v10)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"source_project_id\":"
		out.RawString(prefix)
		out.Int(int(in.SourceProjectID))
	}
	{
		const prefix string = ",\"target_project_id\":"
		out.RawString(prefix)
		out.Int(int(in.TargetProjectID))
	}
	{
		const prefix string = ",\"labels\":"
		out.RawString(prefix)
		if in.Labels == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Labels {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"draft\":"
		out.RawString(prefix)
		out.Bool(bool(in.Draft))
	}
	{
		const prefix string = ",\"work_in_progress\":"
		out.RawString(prefix)
		out.Bool(bool(in.WorkInProgress))
	}
	{
		const prefix string = ",\"milestone\":"
		out.RawString(prefix)
		if in.Milestone == nil {
			out.RawString("null")
		} else {
			(*in.Milestone).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"merge_when_pipeline_succeeds\":"
		out.RawString(prefix)
		out.Bool(bool(in.MergeWhenPipelineSucceeds))
	}
	{
		const prefix string = ",\"merge_status\":"
		out.RawString(prefix)
		out.String(string(in.MergeStatus))
	}
	{
		const prefix string = ",\"detailed_merge_status\":"
		out.RawString(prefix)
		out.String(string(in.DetailedMergeStatus))
	}
	{
		const prefix string = ",\"sha\":"
		out.RawString(prefix)
		out.String(string(in.Sha))
	}
	if true {
		const prefix string = ",\"merge_commit_sha\":"
		out.RawString(prefix)
		out.Raw((in.MergeCommitSha).MarshalJSON())
	}
	if true {
		const prefix string = ",\"squash_commit_sha\":"
		out.RawString(prefix)
		out.Raw((in.SquashCommitSha).MarshalJSON())
	}
	{
		const prefix string = ",\"user_notes_count\":"
		out.RawString(prefix)
		out.Int(int(in.UserNotesCount))
	}
	if true {
		const prefix string = ",\"discussion_locked\":"
		out.RawString(prefix)
		out.Raw((in.DiscussionLocked).MarshalJSON())
	}
	if true {
		const prefix string = ",\"should_remove_source_branch\":"
		out.RawString(prefix)
		out.Raw((in.ShouldRemoveSourceBranch).MarshalJSON())
	}
	{
		const prefix string = ",\"force_remove_source_branch\":"
		out.RawString(prefix)
		out.Bool(bool(in.ForceRemoveSourceBranch))
	}
	{
		const prefix string = ",\"allow_collaboration\":"
		out.RawString(prefix)
		out.Bool(bool(in.AllowCollaboration))
	}
	{
		const prefix string = ",\"allow_maintainer_to_push\":"
		out.RawString(prefix)
		out.Bool(bool(in.AllowMaintainerToPush))
	}
	{
		const prefix string = ",\"web_url\":"
		out.RawString(prefix)
		out.String(string(in.WebURL))
	}
	if in.References != nil {
		const prefix string = ",\"references\":"
		out.RawString(prefix)
		(*in.References).MarshalEasyJSON(out)
	}
	if in.TimeStats != nil {
		const prefix string = ",\"time_stats\":"
		out.RawString(prefix)
		(*in.TimeStats).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"squash\":"
		out.RawString(prefix)
		out.Bool(bool(in.Squash))
	}
	{
		const prefix string = ",\"squash_on_merge\":"
		out.RawString(prefix)
		out.Bool(bool(in.SquashOnMerge))
	}
	{
		const prefix string = ",\"task_completion_status\":"
		out.RawString(prefix)
		if in.TaskCompletionStatus == nil {
			out.RawString("null")
		} else {
			(*in.TaskCompletionStatus).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"has_conflicts\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasConflicts))
	}
	{
		const prefix string = ",\"blocking_discussions_resolved\":"
		out.RawString(prefix)
		out.Bool(bool(in.BlockingDiscussionsResolved))
	}
	if true {
		const prefix string = ",\"approvals_before_merge\":"
		out.RawString(prefix)
		out.Raw((in.ApprovalsBeforeMerge).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MergeRequestModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MergeRequestModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MergeRequestModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MergeRequestModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab5(l, v)
}
func easyjson5af0c543DecodeGithubComStalwartgiraffeCmrInternalGitlab6(in *jlexer.Lexer, out *UserModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "username":
			out.Username = string(in.String())
		case "state":
			out.State = string(in.String())
		case "email":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Email).UnmarshalJSON(data))
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "avatar_url":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.AvatarURL).UnmarshalJSON(data))
			}
		case "web_url":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.WebURL).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5af0c543EncodeGithubComStalwartgiraffeCmrInternalGitlab6(out *jwriter.Writer, in UserModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	if true {
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.Raw((in.Email).MarshalJSON())
	}
	if true {
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	if true {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.Raw((in.AvatarURL).MarshalJSON())
	}
	if true {
		const prefix string = ",\"web_url\":"
		out.RawString(prefix)
		out.Raw((in.WebURL).MarshalJSON())
	}
	out.RawByte('}')
}
