// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  gitlab

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( MergeRequestSlice ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MergeRequestSlice ) UnmarshalJSON([]byte) error { return nil }
func ( MergeRequestSlice ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MergeRequestSlice ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MergeRequestSlice *MergeRequestSlice
