// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gitlab

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9b1fe0f7DecodeGithubComStalwartgiraffeCmrInternalGitlab(in *jlexer.Lexer, out *MergeRequestSlice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(MergeRequestSlice, 0, 0)
			} else {
				*out = MergeRequestSlice{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 MergeRequestModel
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9b1fe0f7EncodeGithubComStalwartgiraffeCmrInternalGitlab(out *jwriter.Writer, in MergeRequestSlice) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v MergeRequestSlice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9b1fe0f7EncodeGithubComStalwartgiraffeCmrInternalGitlab(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MergeRequestSlice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9b1fe0f7EncodeGithubComStalwartgiraffeCmrInternalGitlab(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MergeRequestSlice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9b1fe0f7DecodeGithubComStalwartgiraffeCmrInternalGitlab(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MergeRequestSlice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9b1fe0f7DecodeGithubComStalwartgiraffeCmrInternalGitlab(l, v)
}
